#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# create a virtual environment
python -m venv FaaS
# activate the virtual environment
source FaaS/bin/activate
# Install dependencies
pip install -r requirements.txt